type Mutation {
    signUp(
        firstName: String!,
        lastName: String!,
        email: String!,
        password: String!,
        businessName: String!,
        country: CountryInput!
    ): Auth!
}